config/routes.rb
Rails.application.routes.draw do
  resources :cutters do
  	resources :comments
  end
  
  root 'cutters#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :cutter
end

app/models/cutter.rb
class Cutter < ApplicationRecord
	has_many :comments
	validates :name, presence: true
	validates :description, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @cutter = Cutter.find(params[:cutter_id])
    @comment = @cutter.comments.create(comment_params)
    redirect_to cutter_path(@cutter)
  end

    def destroy
    @cutter = Cutter.find(params[:cutter_id])
    @comment = @cutter.comments.find(params[:id])
    @comment.destroy
    redirect_to cutter_path(@cutter)
  end
 
  private
    def comment_params
      params.require(:comment).permit(:commenter, :body)
    end
end

app/controllers/cutters_controller.rb
class CuttersController < ApplicationController
  before_action :set_cutter, only: [:show, :edit, :update, :destroy]

  # GET /cutters
  # GET /cutters.json
  def index
    @cutters = Cutter.all
  end

  # GET /cutters/1
  # GET /cutters/1.json
  def show
  end

  # GET /cutters/new
  def new
    @cutter = Cutter.new
  end

  # GET /cutters/1/edit
  def edit
  end

  # POST /cutters
  # POST /cutters.json
  def create
    @cutter = Cutter.new(cutter_params)

    respond_to do |format|
      if @cutter.save
        format.html { redirect_to @cutter, notice: 'Cutter was successfully created.' }
        format.json { render :show, status: :created, location: @cutter }
      else
        format.html { render :new }
        format.json { render json: @cutter.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cutters/1
  # PATCH/PUT /cutters/1.json
  def update
    respond_to do |format|
      if @cutter.update(cutter_params)
        format.html { redirect_to @cutter, notice: 'Cutter was successfully updated.' }
        format.json { render :show, status: :ok, location: @cutter }
      else
        format.html { render :edit }
        format.json { render json: @cutter.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cutters/1
  # DELETE /cutters/1.json
  def destroy
    @cutter.destroy
    respond_to do |format|
      format.html { redirect_to cutters_url, notice: 'Cutter was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cutter
      @cutter = Cutter.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def cutter_params
      params.require(:cutter).permit(:name, :description)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/cutters_helper.rb
module CuttersHelper
end

app/views/comments/_comment.html.erb
  <p>
    <strong>Commenter:</strong>
    <%= comment.commenter %>
  </p>
 
  <p>
    <strong>Comment:</strong>
    <%= comment.body %>
  </p>

  <p>
  <%= link_to 'Destroy Comment', [comment.cutter, comment], method: :delete,
  		data: {confirm: 'Are you sure?'} %>
  </p>

app/views/comments/_form.html.erb
<%= form_for([@cutter, @cutter.comments.build]) do |f| %>
  <p>
    <%= f.label :commenter %><br>
    <%= f.text_field :commenter %>
  </p>
  <p>
    <%= f.label :body %><br>
    <%= f.text_area :body %>
  </p>
  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/cutters/_form.html.erb
<%= form_for(cutter) do |f| %>
  <% if cutter.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(cutter.errors.count, "error") %> prohibited this cutter from being saved:</h2>

      <ul>
      <% cutter.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :description %>
    <%= f.text_area :description %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/cutters/edit.html.erb
<h1>Editing Cutter</h1>

<%= render 'form', cutter: @cutter %>

<%= link_to 'Show', @cutter %> |
<%= link_to 'Back', cutters_path %>

app/views/cutters/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Cutters</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @cutters.each do |cutter| %>
      <tr>
        <td><%= cutter.name %></td>
        <td><%= cutter.description %></td>
        <td><%= link_to 'Show', cutter %></td>
        <td><%= link_to 'Edit', edit_cutter_path(cutter) %></td>
        <td><%= link_to 'Destroy', cutter, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Cutter', new_cutter_path %>

app/views/cutters/new.html.erb
<h1>New Cutter</h1>

<%= render 'form', cutter: @cutter %>

<%= link_to 'Back', cutters_path %>

app/views/cutters/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @cutter.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @cutter.description %>
</p>

<h2>Comments</h2>
<%= render @cutter.comments %>

<h2>Add a comment:</h2>
<%= render 'comments/form' %>

<%= link_to 'Edit', edit_cutter_path(@cutter) %> |
<%= link_to 'Back', cutters_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Page</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>